services:
  postgres:
    image: postgres:15
    container_name: postgres_api
    restart: unless-stopped
    environment:
      POSTGRES_DB: apidb
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5433:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data

volumes:
  postgres-data:
